# Generated by Django 4.1 on 2022-08-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='previousClose_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='previousClose_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='price_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='price_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='previousClose_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='previousClose_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='price_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='silver',
            name='price_kg',
            field=models.FloatField(null=True),
        ),
    ]
